export function demoData() {
  const clients = [
    {
      id: "demo-client-1",
      client_code: "RE-000001",
      full_name: "Arif Rahman",
      email: "arif@example.com",
      phone: "+880 1700 000001",
      country: "Bangladesh",
      address: "Dhaka, Bangladesh",
      occupation: "Business owner",
      emergency_contact: "",
      status: "active",
      auth_user_id: "demo-owner",
      created_at: "2026-09-01T09:00:00Z",
    },
    {
      id: "demo-client-2",
      client_code: "RE-000002",
      full_name: "Nadia Ahmed",
      email: "nadia@example.com",
      phone: "+880 1700 000002",
      country: "United Kingdom",
      address: "London, United Kingdom",
      occupation: "Architect",
      emergency_contact: "",
      status: "active",
      created_at: "2026-09-02T09:00:00Z",
    },
    {
      id: "demo-client-3",
      client_code: "RE-000003",
      full_name: "Fahim Hasan",
      email: "fahim@example.com",
      phone: "+880 1700 000003",
      country: "Bangladesh",
      address: "Chattogram, Bangladesh",
      occupation: "Engineer",
      emergency_contact: "",
      status: "active",
      created_at: "2026-09-03T09:00:00Z",
    },
  ];
  const villas = [
    {
      id: "demo-villa-1",
      client_id: clients[0].id,
      villa_number: "A-012",
      villa_type: "The Premium",
      block: "Garden Avenue",
      plot_size: "10 Katha",
      stage: "Structure",
      progress: 62,
      handover_date: "2027-12-31",
      updated_at: "2026-09-12T09:00:00Z",
    },
    {
      id: "demo-villa-2",
      client_id: clients[1].id,
      villa_number: "B-028",
      villa_type: "The Classic",
      block: "Parkside",
      plot_size: "5 Katha",
      stage: "Foundation",
      progress: 28,
      handover_date: "2028-03-31",
      updated_at: "2026-09-10T09:00:00Z",
    },
    {
      id: "demo-villa-3",
      client_id: clients[2].id,
      villa_number: "C-006",
      villa_type: "The Estate",
      block: "Lakeview",
      plot_size: "20 Katha",
      stage: "Finishing",
      progress: 84,
      handover_date: "2027-09-30",
      updated_at: "2026-09-08T09:00:00Z",
    },
  ];
  const updates = [
    {
      id: "demo-update-1",
      villa_id: villas[0].id,
      title: "Your villa, taking shape",
      body: "The structural phase is progressing. The estate team will share site photography and inspection notes as each milestone is completed.",
      published: true,
      created_at: "2026-09-12T09:00:00Z",
      media: [
        {
          id: "demo-media-1",
          resource_type: "image",
          ready: true,
          caption: "Architectural reference render",
          demoUrl: "/10 katha villa/10-katha.jpg",
        },
      ],
    },
    {
      id: "demo-update-2",
      villa_id: villas[1].id,
      title: "Foundation works underway",
      body: "Foundation preparation and the next site inspection are being coordinated by the project team.",
      published: true,
      created_at: "2026-09-10T09:00:00Z",
      media: [
        {
          id: "demo-media-2",
          resource_type: "image",
          ready: true,
          caption: "Architectural reference render",
          demoUrl: "/5 katha villa/5-katha.jpg",
        },
      ],
    },
    {
      id: "demo-update-3",
      villa_id: villas[2].id,
      title: "Interior finishing review",
      body: "A draft update for the next owner communication. Publish once the site review is complete.",
      published: false,
      created_at: "2026-09-08T09:00:00Z",
      media: [],
    },
  ];
  return { clients, villas, updates };
}

export const villaRender = (type) =>
  ({
    "The Classic": "/5 katha villa/5-katha.jpg",
    "The Premium": "/10 katha villa/10-katha.jpg",
    "The Estate": "/20 katha villa/20-katha.jpg",
  })[type] || "/5 katha villa/5-katha.jpg";
